# Generated by Django 3.1.1 on 2020-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('receivedTime', models.DateTimeField(auto_now_add=True)),
                ('dateReceived', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=False)),
                ('customer_name', models.CharField(max_length=50)),
            ],
        ),
    ]
