# Generated by Django 3.1.1 on 2020-10-27 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20201027_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='customer_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='received',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
