# Generated by Django 3.1.1 on 2020-10-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20201028_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sold',
            name='customer_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sold',
            name='customer_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sold',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
