# Generated by Django 3.1.1 on 2020-10-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20201028_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='usersold',
        ),
        migrations.AddField(
            model_name='sold',
            name='issued_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
