# Generated by Django 3.1.1 on 2020-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20201028_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='issued_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
