# Generated by Django 3.1.1 on 2020-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20201028_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='issued_by',
        ),
    ]
