# Generated by Django 3.1.1 on 2020-10-26 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(default=1,auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('receivedTime', models.DateTimeField(auto_now_add=True)),
                ('dateReceived', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('purchaser_user', models.ForeignKey(default=1,on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
