# Generated by Django 3.1.1 on 2020-10-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sold',
        ),
    ]
