# Generated by Django 3.1.1 on 2020-10-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soldout', '0003_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='purchaser_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
